### ISSUE TITLE
write_pin hardcoded to port A

### ISSUE THREAD

**Issue by tjac** [nationelectronics/nationelectronics_C_libraries#1]
In iope.c, there seems to be a mistake:

void write_pin(char address, char port, char pin, char value) {
   /*
    write to an individual pin
    port PORTA or PORTB
    pins 0 to 7
    value 1 = logic level high (5V), 0 = logic level low (GND)
    */
   port=(port)?GPIOB:GPIOA; 
   char cval = 0;
   cval = read_byte_data(address, GPIOA);
   cval = updatebyte(cval, pin, value);
   write_byte_data(address, GPIOA, cval);
}

The read_byte_data and write_byte_data are hardcoded to GPIOA so regardless of the port desired, it will always access port A

**Comment by nationelectronics** [comment]
Thanks tjac for your  observation. The code was corrected.
